NumPy is a Python library that provides support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on them efficiently.


In [1]:
!pip install numpy

In [4]:
import numpy as np

arr1 = np.array([1,3,4,5,5])
print(type(arr1))
print(arr1.shape)


<class 'numpy.ndarray'>
(5,)


In [ ]:
arr2 = np.array([1,3,4,5,5])
arr2.reshape(1,5) # 2d array

array([[1, 3, 4, 5, 5]])

In [8]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
#vectorised operations


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Arithmetic operations
print("a + b =", a + b)  # Element-wise addition
print("a - b =", a - b)  # Element-wise subtraction
print("a * b =", a * b)  # Element-wise multiplication
print("a / b =", a / b)  # Element-wise division

a + b = [5 7 9]
a - b = [-3 -3 -3]
a * b = [ 4 10 18]
a / b = [0.25 0.4  0.5 ]


In [17]:
#universal function

arr = np.array([4, 36, 81])

print(np.sqrt(arr))
print(np.exp(arr))
print(np.sin(arr))



[2. 6. 9.]
[5.45981500e+01 4.31123155e+15 1.50609731e+35]
[-0.7568025  -0.99177885 -0.62988799]


In [ ]:
#slicing and indexing
arr_2d = np.array(
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ]
)

print(arr_2d)
print('\n')

print(arr_2d[0][1])
print('\n')

print(arr_2d[1:])
print('\n')

print(arr_2d[1:, 2:])
print('\n')




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2


[[ 5  6  7  8]
 [ 9 10 11 12]]


[[ 7  8]
 [11 12]]


In [27]:
#normalization
#to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

#calculate mean and sd
mean = np.mean(data)
std_dev = np.std(data)

#normalize the data
normalized_data = (data - mean) / std_dev
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [28]:
#logical operations
data = np.array([1,2,3,4,5,6,7,8,9])

data[data > 5]

array([6, 7, 8, 9])